#!/bin/sh

action=${1:-}
monitor=$(swaymsg -t get_outputs --raw 2>/dev/null \
    | jq -r '.[] | select(.focused == true) | .name' \
    | head -n 1)

if [ -n "$monitor" ]; then
    set -- --monitor "$monitor"
else
    set --
fi

case "$action" in
    volume-up)      exec swayosd-client "$@" --output-volume +5 --max-volume 120 ;;
    volume-down)    exec swayosd-client "$@" --output-volume -5 --max-volume 120 ;;
    volume-mute)    exec swayosd-client "$@" --output-volume mute-toggle ;;
    mic-mute)       exec swayosd-client "$@" --input-volume mute-toggle ;;
    brightness-up)  exec swayosd-client "$@" --brightness +5 --device amdgpu_bl0 ;;
    brightness-down) exec swayosd-client "$@" --brightness -5 --device amdgpu_bl0 ;;
    play-pause)     exec swayosd-client "$@" --playerctl play-pause ;;
    previous)       exec swayosd-client "$@" --playerctl prev ;;
    next)           exec swayosd-client "$@" --playerctl next ;;
    *)
        printf 'unknown OSD action: %s\n' "$action" >&2
        exit 2
        ;;
esac
