# Saved automatically from the graphical display settings.
profile dual-display {
    output HDMI-A-1 enable mode 1920x1080@60Hz position 0,0 scale 1.0 transform normal
    output eDP-1 enable mode 1920x1080@59.997Hz position 1920,0 scale 1.0 transform normal
}
